// ============================================
// AAROGYA AI — CROSS-MODULE HEALTH CONTEXT STORE
// The "brain" that connects all health modules.
//
// This store enables cross-module intelligence:
// - Lab findings → trigger disease prediction updates
// - Imaging findings → update predictive trajectory
// - Disease risk → escalate decision recommendations
// - All findings → unified health timeline
//
// Uses Zustand for reactive state management.
// ============================================

import { create } from 'zustand';

// --- Types ---

export type FindingSeverity = 'normal' | 'borderline' | 'abnormal' | 'critical';
export type FindingSource = 'lab_report' | 'xray' | 'skin' | 'symptom' | 'disease_prediction' | 'vitals' | 'manual';

export interface HealthFinding {
  id: string;
  source: FindingSource;
  timestamp: string;
  category: string;           // e.g., 'Blood Count', 'Cardiac', 'Diabetes', 'Respiratory'
  name: string;               // e.g., 'Hemoglobin', 'Chest X-ray', 'Headache'
  value?: string;             // e.g., '11.2 g/dL', 'Cardiomegaly observed'
  severity: FindingSeverity;
  confidence: number;         // 0-100
  details?: string;
  recommendedAction?: string;
}

export interface CrossModuleInsight {
  id: string;
  timestamp: string;
  triggeredBy: string[];       // finding IDs that triggered this insight
  modules: FindingSource[];    // which modules are involved
  insight: string;
  urgency: 'routine' | 'within_week' | 'urgent' | 'emergency';
  recommendedActions: string[];
  causalChain: string;         // human-readable cause → mechanism → effect
}

export interface DecisionRecommendation {
  id: string;
  timestamp: string;
  priority: 'low' | 'medium' | 'high' | 'critical';
  action: string;
  reason: string;
  source: string;             // which module/insight generated this
  estimatedImpact: 'low' | 'moderate' | 'high';
}

interface HealthContextState {
  // --- Findings from all modules ---
  findings: HealthFinding[];

  // --- Cross-module insights generated by reasoning engine ---
  insights: CrossModuleInsight[];

  // --- Decision recommendations ---
  recommendations: DecisionRecommendation[];

  // --- User health profile (shared memory) ---
  profile: {
    age?: number;
    gender?: string;
    knownConditions: string[];
    medications: string[];
    riskFactors: string[];
  };

  // --- Actions ---
  addFinding: (finding: Omit<HealthFinding, 'id' | 'timestamp'>) => void;
  removeFinding: (id: string) => void;
  clearFindings: () => void;
  updateProfile: (updates: Partial<HealthContextState['profile']>) => void;
  dismissInsight: (id: string) => void;
  dismissRecommendation: (id: string) => void;

  // --- Derived selectors ---
  getFindingsBySource: (source: FindingSource) => HealthFinding[];
  getFindingsBySeverity: (severity: FindingSeverity) => HealthFinding[];
  getCriticalFindings: () => HealthFinding[];
  getActiveInsights: () => CrossModuleInsight[];
  getActiveRecommendations: () => DecisionRecommendation[];
}

// --- Cross-module reasoning engine ---

function generateInsights(findings: HealthFinding[], profile: HealthContextState['profile']): { insights: CrossModuleInsight[]; recommendations: DecisionRecommendation[] } {
  const insights: CrossModuleInsight[] = [];
  const recommendations: DecisionRecommendation[] = [];
  const now = new Date().toISOString();

  // Rule 1: High glucose + high HbA1c → diabetes risk escalation
  const glucoseFinding = findings.find(f => f.name.toLowerCase().includes('glucose') || f.name.toLowerCase().includes('fasting glucose'));
  const hba1cFinding = findings.find(f => f.name.toLowerCase().includes('hba1c'));
  if (glucoseFinding && hba1cFinding && (glucoseFinding.severity === 'abnormal' || hba1cFinding.severity === 'abnormal')) {
    insights.push({
      id: `insight-diabetes-${Date.now()}`,
      timestamp: now,
      triggeredBy: [glucoseFinding.id, hba1cFinding.id],
      modules: ['lab_report', 'disease_prediction'],
      insight: 'Elevated glucose and HbA1c detected — diabetes risk is significantly elevated',
      urgency: 'within_week',
      recommendedActions: ['Consult endocrinologist', 'Reduce sugar intake', 'Start 30-min daily walk'],
      causalChain: 'High glucose + high HbA1c → indicates sustained hyperglycemia → diabetes risk escalation',
    });
    recommendations.push({
      id: `rec-diabetes-${Date.now()}`,
      timestamp: now,
      priority: 'high',
      action: 'Consult endocrinologist for diabetes evaluation',
      reason: 'Lab findings show elevated glucose and HbA1c',
      source: 'lab_report + disease_prediction',
      estimatedImpact: 'high',
    });
  }

  // Rule 2: Abnormal lipids + high BP → cardiac risk
  const cholesterolFinding = findings.find(f => f.name.toLowerCase().includes('cholesterol') || f.name.toLowerCase().includes('ldl'));
  const bpFinding = findings.find(f => f.category.toLowerCase().includes('vitals') || f.name.toLowerCase().includes('blood pressure'));
  if (cholesterolFinding && cholesterolFinding.severity === 'abnormal' && bpFinding && bpFinding.severity !== 'normal') {
    insights.push({
      id: `insight-cardiac-${Date.now()}`,
      timestamp: now,
      triggeredBy: [cholesterolFinding.id, bpFinding.id],
      modules: ['lab_report', 'vitals', 'disease_prediction'],
      insight: 'Abnormal cholesterol combined with elevated blood pressure — cardiac risk factors compound',
      urgency: 'within_week',
      recommendedActions: ['Consult cardiologist', 'DASH diet', 'Reduce salt intake', 'Regular cardio exercise'],
      causalChain: 'High LDL + elevated BP → atherosclerotic progression → increased cardiac event risk',
    });
  }

  // Rule 3: Critical lab value → immediate escalation
  const criticalFindings = findings.filter(f => f.severity === 'critical');
  criticalFindings.forEach(f => {
    insights.push({
      id: `insight-critical-${f.id}`,
      timestamp: now,
      triggeredBy: [f.id],
      modules: [f.source, 'decision'],
      insight: `Critical value detected: ${f.name} (${f.value}) — requires immediate medical attention`,
      urgency: 'emergency',
      recommendedActions: ['Seek immediate medical care', 'Call 108 if symptoms are severe'],
      causalChain: `${f.name} critically abnormal → organ function at risk → immediate intervention needed`,
    });
    recommendations.push({
      id: `rec-critical-${f.id}`,
      timestamp: now,
      priority: 'critical',
      action: `Seek immediate medical attention for critical ${f.name}`,
      reason: f.details || `Critical value: ${f.value}`,
      source: f.source,
      estimatedImpact: 'high',
    });
  });

  // Rule 4: Imaging severity → predictive trajectory update
  const imagingFindings = findings.filter(f => (f.source === 'xray' || f.source === 'skin') && (f.severity === 'moderate' || f.severity === 'abnormal' || f.severity === 'critical'));
  imagingFindings.forEach(f => {
    if (!insights.some(i => i.triggeredBy.includes(f.id))) {
      insights.push({
        id: `insight-imaging-${f.id}`,
        timestamp: now,
        triggeredBy: [f.id],
        modules: [f.source, 'disease_prediction', 'predictive'],
        insight: `Imaging finding (${f.name}) with ${f.severity} severity — may impact health trajectory`,
        urgency: f.severity === 'critical' ? 'urgent' : 'within_week',
        recommendedActions: ['Follow up with specialist', 'Schedule comparative imaging in 3-6 months'],
        causalChain: `${f.name} (${f.severity}) → structural anomaly detected → may progress if untreated`,
      });
    }
  });

  // Rule 5: Multiple abnormal findings → systemic risk
  const abnormalCount = findings.filter(f => f.severity === 'abnormal' || f.severity === 'critical').length;
  if (abnormalCount >= 3) {
    insights.push({
      id: `insight-systemic-${Date.now()}`,
      timestamp: now,
      triggeredBy: findings.filter(f => f.severity === 'abnormal' || f.severity === 'critical').map(f => f.id),
      modules: ['lab_report', 'disease_prediction', 'predictive', 'decision'],
      insight: `${abnormalCount} abnormal findings detected across modules — suggests systemic health concern`,
      urgency: 'within_week',
      recommendedActions: ['Comprehensive health checkup', 'Consult general physician first', 'Monitor vitals daily'],
      causalChain: `Multiple abnormalities (${abnormalCount}) → systemic rather than isolated issue → comprehensive evaluation needed`,
    });
    recommendations.push({
      id: `rec-systemic-${Date.now()}`,
      timestamp: now,
      priority: 'high',
      action: 'Schedule comprehensive health checkup',
      reason: `${abnormalCount} abnormal findings across multiple systems`,
      source: 'cross_module_reasoning',
      estimatedImpact: 'high',
    });
  }

  // Rule 6: Symptom + lab correlation
  const symptomFindings = findings.filter(f => f.source === 'symptom');
  symptomFindings.forEach(symptom => {
    const relatedLabs = findings.filter(f => f.source === 'lab_report' && f.severity !== 'normal' &&
      (symptom.category.toLowerCase().includes('head') && f.name.toLowerCase().includes('hemoglobin')));
    if (relatedLabs.length > 0) {
      relatedLabs.forEach(lab => {
        insights.push({
          id: `insight-symptom-lab-${symptom.id}-${lab.id}`,
          timestamp: now,
          triggeredBy: [symptom.id, lab.id],
          modules: ['symptom', 'lab_report'],
          insight: `Symptom "${symptom.name}" may correlate with abnormal ${lab.name}`,
          urgency: 'routine',
          recommendedActions: ['Discuss correlation with your doctor'],
          causalChain: `${symptom.name} + abnormal ${lab.name} → possible underlying cause identified`,
        });
      });
    }
  });

  return { insights, recommendations };
}

// --- Store ---

export const useHealthContext = create<HealthContextState>((set, get) => ({
  findings: [],
  insights: [],
  recommendations: [],
  profile: {
    knownConditions: [],
    medications: [],
    riskFactors: [],
  },

  addFinding: (finding) => {
    const newFinding: HealthFinding = {
      ...finding,
      id: `finding-${Date.now()}-${Math.random().toString(36).substring(2, 8)}`,
      timestamp: new Date().toISOString(),
    };

    set((state) => {
      const findings = [...state.findings.filter(f => !(f.source === newFinding.source && f.name === newFinding.name)), newFinding];
      const { insights, recommendations } = generateInsights(findings, state.profile);
      return { findings, insights, recommendations };
    });
  },

  removeFinding: (id) => {
    set((state) => {
      const findings = state.findings.filter(f => f.id !== id);
      const { insights, recommendations } = generateInsights(findings, state.profile);
      return { findings, insights, recommendations };
    });
  },

  clearFindings: () => set({ findings: [], insights: [], recommendations: [] }),

  updateProfile: (updates) => {
    set((state) => {
      const profile = { ...state.profile, ...updates };
      const { insights, recommendations } = generateInsights(state.findings, profile);
      return { profile, insights, recommendations };
    });
  },

  dismissInsight: (id) => set((state) => ({
    insights: state.insights.filter(i => i.id !== id),
  })),

  dismissRecommendation: (id) => set((state) => ({
    recommendations: state.recommendations.filter(r => r.id !== id),
  })),

  // --- Selectors ---
  getFindingsBySource: (source) => get().findings.filter(f => f.source === source),
  getFindingsBySeverity: (severity) => get().findings.filter(f => f.severity === severity),
  getCriticalFindings: () => get().findings.filter(f => f.severity === 'critical'),
  getActiveInsights: () => get().insights,
  getActiveRecommendations: () => get().recommendations.sort((a, b) => {
    const order = { critical: 0, high: 1, medium: 2, low: 3 };
    return order[a.priority] - order[b.priority];
  }),
}));
